### ISSUE TITLE
Rename fix to mix

### ISSUE THREAD

**Issue by burak-kara** [AItransCompetition/Short-Video-Streaming-Challenge#11]
Hi,

After the renaming from fix to mix  (#10), the "fixed"s on line 12 of run.py remain the same. I think those should be renamed to "mixed " as well. Otherwise, it gives the following error as expected;
`Traceback (most recent call last):
  File "run.py", line 243, in <module>
    assert args.trace in ["mixed", "high", "low", "medium"]
AssertionError`

This 
`
parser.add_argument('--trace', type=str, default='fixed', help='The network trace you are testing (fixed, high, low, medium, middle)')
`
should be this
`
parser.add_argument('--trace', type=str, default='mixed', help='The network trace you are testing (mixed, high, low, medium, middle)')
`

**Comment by liy1shu** [comment]
Thanks! 
Its our mistake, we'll change it now.
