### ISSUE TITLE
Different os implements leads to different results

### ISSUE THREAD

**Issue by scalar42** [AItransCompetition/Short-Video-Streaming-Challenge#15]
https://github.com/AItransCompetition/Short-Video-Streaming-Challenge/blob/1762ffee2a83d87476c062adeb8f90b7bc27f3e5/simulator/video_player.py#L22-L24

The line here leads to different `dirs` results, which can further lead to different QoE results.

`print(videos)` outputs can be: `['1_tj', '2_EDG', '3_gy', '4_dx', '5_ss', '6_jt', '7_yd']`, while on others: `['2_EDG', '1_tj', '3_gy', '5_ss', '4_dx', '6_jt', '7_yd']`

Need to add `videos.sort()` to prevent these cases.
```python
 for root, dirs, files in os.walk(VIDEO_SIZE_FILE): 
     videos = dirs 
     videos.sort()
     break 
```

**Comment by liy1shu** [comment]
Ok. We've updated it.

**Comment by scalar42** [comment]
thanks, I'll close this then.
