### ISSUE TITLE
Potential Issues in Smooth Calculation

### ISSUE THREAD

**Issue by king-wk** [AItransCompetition/Short-Video-Streaming-Challenge#16]
For the calculation of smooth, when downloading a video chunk, if the downloaded chunk will be played, calculate the smooth of watching the chunk. When the chunk_id is 0, it means that the video chunk played before this chunk is in the last video, but ```last_chunk_bitrate[download_video_id - 1]``` records the bitrate of the last downloaded chunk of the last video, instead of the chunk which will be played lastly of the last video, which may not be played continuously with this downloaded chunk, so smooth canot be calculated with two video chunks that will not play continuously.

```python
def get_smooth(net_env, download_video_id, chunk_id, quality):
    if download_video_id == 0 and chunk_id == 0:  # is the first chunk of all
        return 0
    if chunk_id == 0:  # needs to find the last chunk of the last video
        last_bitrate = last_chunk_bitrate[download_video_id - 1]
    else:
        last_bitrate = net_env.players[download_video_id - net_env.get_start_video_id()].get_downloaded_bitrate()[chunk_id - 1]
    return abs(quality - VIDEO_BIT_RATE[last_bitrate])
```

Please correct me if my understanding is wrong. Look forward to your response. Thanks.

**Comment by liy1shu** [comment]
![WechatIMG1295](https://user-images.githubusercontent.com/30770342/167356139-b844c569-14c0-4f69-9a7b-c16b08489014.jpeg)
We only update last_chunk_bitrate with the last chunk that will be played in a video, as shown in the pic (`run.py` line 117-119). Maybe its the name of this list that caused confusion.
Does this solve your confusion? Feel free to reach us again if my understanding is wrong.

**Comment by king-wk** [comment]
Thanks for you reply. But I don't think you understand my problem. When downloading the first chunk of this video, **it should use the last played chunk of the last video with this chunk to calculate smooth**. But if **the last played chunk of the last video has not been downloaded**( ```last_chunk_bitrate[download_video_id - 1]``` only record the last downloaded chunk instead of the last played chunk), which means **the bitrate of the last played chunk of the last video has not been recorded**, it will calculate a wrong smooth value.

**Comment by liy1shu** [comment]
Oh, I understand now. Its my problem. Thanks, we'll fix it today.

**Comment by king-wk** [comment]
Thanks a lot!

**Comment by imageCompression1995** [comment]
Hello, should we reset the global variable **last_chunk_bitrate** at each test trace for a more accurate smooth calculation?

**Comment by king-wk** [comment]
> Hello, should we reset the global variable **last_chunk_bitrate** at each test trace for a more accurate smooth calculation?

I think you are right. You can open a new issue to discuss this problem.
