### ISSUE TITLE
Little Bug in Smooth Calculation

### ISSUE THREAD

**Issue by king-wk** [AItransCompetition/Short-Video-Streaming-Challenge#18]
in line 131 of run.py,
 ```smooth += abs(quality - VIDEO_BIT_RATE[next_bitrate])```
but in line 133, 
```smooth = get_smooth(net_env, download_video_id, download_chunk, quality)``` 
the value of smooth will be covered.
I think it should be 
```smooth += get_smooth(net_env, download_video_id, download_chunk, quality)```
Please correct me if my understanding is wrong. Thanks.

**Comment by liy1shu** [comment]
I check the code in this repo and it is += indeed. 
Weird, is my github not working properly? Please check it again, looking forward to your reply.

**Comment by king-wk** [comment]
I remember what I saw was '+' at that time, maybe my github or my mind gets something wrong, very sorry about that.
