### ISSUE TITLE
Potential Issues in Log Operation

### ISSUE THREAD

**Issue by tzj99** [AItransCompetition/Short-Video-Streaming-Challenge#4]
As described in Readme,
![image](https://user-images.githubusercontent.com/82486213/164590411-5c6e6817-e1e2-4bcb-a75f-ccafe06bcc5c.png)
And from my point of view, the log of the quickstart algorithm should be printed in log_fixpreload.txt.
However, when I tested the quickstart algorithm, I found that those logs were printed in log.txt instead. This probably because the assignment operation failed, as shown in the figure below.
![image](https://user-images.githubusercontent.com/82486213/164590533-116dc994-9a72-4a04-b8a4-65c6e66290dc.png)
This also happens in other similar cases.
![image](https://user-images.githubusercontent.com/82486213/164591536-232d2a6a-3908-4591-84a4-26afee3d23e9.png) 
Sorry if I have misunderstood.

**Comment by liy1shu** [comment]
Thanks for your issue!

Sorry, It's our mistake (Somehow it managed to run normally on my laptop before.) We've fixed it now by adding global to the variable LOG_FILE.
