### ISSUE TITLE
Potential Issues in QoE Calculation and Video Play

### ISSUE THREAD

**Issue by king-wk** [AItransCompetition/Short-Video-Streaming-Challenge#6]
- First, the calculation of QoE is implemented as:
```
one_step_QoE = alpha * quality / 1000. - beta * rebuf / 1000. - gamma * smooth / 1000.
```
For the calculation of smooth, when downloading a video chunk, if the downloaded block will be played, calculate the smooth of watching the chunk.
```python
# last downloaded chunk id
download_chunk = net_env.players[download_video_id - net_env.get_start_video_id()].get_chunk_counter()
if max_watch_chunk_id >= download_chunk:  # the last downloaded chunk of this video will be played
    quality = VIDEO_BIT_RATE[bit_rate]
    if last_bitrate != -1:  # is not the first chunk to play
        smooth = abs(quality - VIDEO_BIT_RATE[last_bitrate])
        # print("downloading ", download_video_id, "chunk ", download_chunk, ", bitrate switching from ", last_bitrate, " to ", bit_rate)
    last_bitrate = bit_rate
```
But in line 91 of run.py, the download_chunk is the last downloaded chunk id of the vode download_video_id, and if max_watch_chunk_id >= download_chunk, it should mean the last downloaded chunk will be played not this downloaded chunk. What's more, last_bitrate records the bitrate of the last downloaded chunk, instead of the last downloaded chunk of video download_video_id, which may not be played continuously with this downloaded chunk, so smooth canot be calculated with two video chunks that will not play continuously.

- Second, in simulator\controller.py, it add first_play to make play timeline (divided by 1000.0 to calculate play chunk ) and the retention duration equal.
```python
first_play = min(self.players[0].get_video_len(), self.user_models[0].get_ret_duration()) - self.players[0].play_timeline
play_tm, buffer = self.players[0].video_play(min(time_len, first_play))
```

But in line 90, it will make time_len be 0 instead of the rest of the time after watching the video.
```python
time_len = play_tm - min(self.players[0].get_video_len(), self.user_models[0].get_ret_duration())
```

**Comment by liy1shu** [comment]
Thanks! Your question is very valuable.
We've checked and its our mistake. We'll push the changes to the repository soon.
