### ISSUE TITLE
Wrong sample command in "Run a baseline algorithm" part

### ISSUE THREAD

**Issue by chajiuqqq** [AItransCompetition/Short-Video-Streaming-Challenge#7]
In  "Run a baseline algorithm" part, it shows that these codes are used to run a baseline algorithm.
```
python run.py --baseline fixed_preload
python run.py --baseline no_preload
```
However it throws `UnboundLocalError: local variable 'Solution' referenced before assignment`, it seems that something wrong in the argument controlling flow.

After reading the `test()` function in run.py, the correct commands maybe:

```
python run.py --baseline no_save
python run.py --quickstart fixed_preload
```

And it outputs Scores, Bandwidth Usage and so on.

Hope it useful.

**Comment by liy1shu** [comment]
Sorry, this is our negligence when updating README. We will change it soon.
Thanks!
