### ISSUE TITLE
Potential issues in the ‘short_video_load_trace’ file

### ISSUE THREAD

**Issue by Honeybadger-360** [AItransCompetition/Short-Video-Streaming-Challenge#8]
There is a small bug in the file.
When loading a trace, ‘cooked_files’ is a **list collection**, and sorting it directly has no effect. I think line 10 code can be modified to
```ruby
    cooked_files.sort(key=lambda x:int(x))
```
Please correct me if my understanding is wrong. Look forward to your response.

**Comment by liy1shu** [comment]
Thanks! 
You are right, sorting numbers as strings gives the wrong result. We will fix it soon.
