### ISSUE TITLE
why need to the size into preload  size

### ISSUE THREAD

**Issue by bupt-steven** [AItransCompetition/Short-Video-Streaming-Challenge#9]
https://github.com/AItransCompetition/Short-Video-Streaming-Challenge/blob/f18ae56b6bd62cddfa6d003635c48591eeb52207/simulator/video_player.py#L71

**Comment by bupt-steven** [comment]
The interface just provides the video size map ,why need to add the preload_size

**Comment by liy1shu** [comment]
Thanks!
This is indeed a weird logic. We'll move the update of preload_size to another function. Sorry for the confusion!
